In [1]:
import pandas as pd

In [2]:
employees = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name="Employees"
)

In [3]:
employees.head()

   EmployeeID     Name Department        City  Salary
0         101    Alice         IT     Chennai   60000
1         102      Bob         HR  Coimbatore   55000
2         103  Charlie    Finance   Bangalore   75000
3         104    David         IT     Chennai   65000
4         105      Eva         HR     Madurai   52000

In [4]:
targets = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name="Targets"
)

In [6]:
sales = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name="Sales"
)

In [7]:
all_sheets = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name=None
)

In [8]:
type(all_sheets)

dict

In [9]:
employees = all_sheets["Employees"]
sales = all_sheets["Sales"]
targets = all_sheets["Targets"]

In [10]:
excel_file = pd.ExcelFile(
    "data/company_data.xlsx"
)

In [11]:
excel_file.sheet_names

['Employees', 'Sales', 'Targets']

In [12]:
sales = pd.read_excel(
    excel_file,
    sheet_name="Sales"
)

In [13]:
sales_details = pd.merge(
    sales,
    employees,
    on="EmployeeID",
    how="left"
)

In [14]:
sales_details.head()

,OrderID,EmployeeID,Product,Category,Quantity,Price,Revenue,Name,Department,City,Salary
0,1001,101,Laptop,Electronics,1,55000,55000,Alice,IT,Chennai,60000
1,1002,102,Chair,Furniture,4,2500,10000,Bob,HR,Coimbatore,55000
2,1003,103,Monitor,Electronics,2,15000,30000,Charlie,Finance,Bangalore,75000
3,1004,104,Keyboard,Electronics,5,1200,6000,David,IT,Chennai,65000
4,1005,105,Laptop,Electronics,2,55000,110000,Eva,HR,Madurai,52000

In [15]:
department_sales = (
    sales_details
    .groupby("Department")["Revenue"]
    .sum()
    .reset_index()
)

In [16]:
department_sales.columns = [
    "Department",
    "Revenue"
]

In [17]:
department_report = pd.merge(
    department_sales,
    targets,
    on="Department",
    how="left"
)

In [18]:
department_report["AchievementPercent"] = (
    department_report["Revenue"]
    / department_report["MonthlyTarget"]
    * 100
)

In [19]:
department_report["AchievementPercent"] = (
    department_report["AchievementPercent"]
    .round(2)
)

In [20]:
def target_status(row):

    if row["Revenue"] >= row["MonthlyTarget"]:
        return "Target Achieved"

    return "Below Target"

In [21]:
department_report["Status"] = (
    department_report.apply(
        target_status,
        axis=1
    )
)

In [22]:
department_report

  Department  Revenue  MonthlyTarget  AchievementPercent           Status
0    Finance    69000         250000               27.60     Below Target
1         HR   120000         100000              120.00  Target Achieved
2         IT    94500         200000               47.25     Below Target
3  Marketing    55000         150000               36.67     Below Target

In [23]:
product_report = (
    sales_details
    .groupby("Product")
    .agg(
        TotalQuantity=("Quantity", "sum"),
        TotalRevenue=("Revenue", "sum"),
        AveragePrice=("Price", "mean")
    )
    .reset_index()
)

In [24]:
column_name=("source_column", "function")

In [25]:
employee_report = (
    sales_details
    .groupby(
        ["EmployeeID", "Name", "Department"]
    )
    .agg(
        Orders=("OrderID", "count"),
        TotalQuantity=("Quantity", "sum"),
        TotalRevenue=("Revenue", "sum")
    )
    .reset_index()
)

In [26]:
employee_report = employee_report.sort_values(
    "TotalRevenue",
    ascending=False
)

In [27]:
with pd.ExcelWriter(
    "output/company_analysis_report.xlsx"
) as writer:

    sales_details.to_excel(
        writer,
        sheet_name="Sales Details",
        index=False
    )

    department_report.to_excel(
        writer,
        sheet_name="Department Report",
        index=False
    )

    product_report.to_excel(
        writer,
        sheet_name="Product Report",
        index=False
    )

    employee_report.to_excel(
        writer,
        sheet_name="Employee Report",
        index=False
    )

In [28]:
employees = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name="Employees",
    usecols=[
        "EmployeeID",
        "Name",
        "Department",
        "City",
        "Salary"
    ]
)

In [29]:
employees = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name="Employees",
    skiprows=1
)

In [30]:
employees = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name="Employees",
    nrows=5
)

In [31]:
employees = pd.read_excel(
    "data/company_data.xlsx",
    sheet_name="Employees",
    na_values=[
        "N/A",
        "NA",
        "-",
        "Unknown"
    ]
)

In [32]:
employees.isna().sum()

EmployeeID    0
Name          0
Department    0
City          0
Salary        0
dtype: int64

In [33]:
print(employees.info())
print(sales.info())
print(targets.info())

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  8 non-null      int64
 1   Name        8 non-null      str
 2   Department  8 non-null      str
 3   City        8 non-null      str
 4   Salary      8 non-null      int64
dtypes: int64(2), str(3)
memory usage: 452.0 bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     10 non-null     int64
 1   EmployeeID  10 non-null     int64
 2   Product     10 non-null     str
 3   Category    10 non-null     str
 4   Quantity    10 non-null     int64
 5   Price       10 non-null     int64
 6   Revenue     10 non-null     int64
dtypes: int64(5), str(2)
memory usage: 692.0 bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Department     4 non-null      str
 1   MonthlyTarget  4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 196.0 bytes
None

In [34]:
print(
    employees["EmployeeID"].duplicated().sum()
)

0

In [35]:
print(
    employees["EmployeeID"].isna().sum()
)

0

In [36]:
print(
    sales["Revenue"].isna().sum()
)

0

In [37]:
sales["CalculatedRevenue"] = (
    sales["Quantity"] *
    sales["Price"]
)

In [38]:
sales["RevenueMatches"] = (
    sales["Revenue"] ==
    sales["CalculatedRevenue"]
)

In [39]:
sales["RevenueMatches"].value_counts()

RevenueMatches
True    10
Name: count, dtype: int64

In [40]:
sales = sales.drop(
    columns=[
        "CalculatedRevenue",
        "RevenueMatches"
    ]
)

In [41]:
employee_report

   EmployeeID     Name Department  Orders  TotalQuantity  TotalRevenue
4         105      Eva         HR       1              2        110000
0         101    Alice         IT       2              3         85000
7         108    Henry  Marketing       1              1         55000
2         103  Charlie    Finance       2              8         45000
5         106    Frank    Finance       1              3         24000
1         102      Bob         HR       1              4         10000
3         104    David         IT       1              5          6000
6         107    Grace         IT       1              5          3500

In [42]:
best_employee = employee_report.iloc[
    employee_report["TotalRevenue"].idxmax()
]

In [43]:
best_employee

EmployeeID           106
Name               Frank
Department       Finance
Orders                 1
TotalQuantity          3
TotalRevenue       24000
Name: 5, dtype: object

In [44]:
best_product = product_report.iloc[
    product_report["TotalRevenue"].idxmax()
]

In [45]:
best_department = department_report.iloc[
    department_report["Revenue"].idxmax()
]

In [46]:
summary = pd.DataFrame({
    "Metric": [
        "Total Revenue",
        "Total Orders",
        "Best Employee",
        "Best Product",
        "Best Department"
    ],

    "Value": [
        sales["Revenue"].sum(),
        len(sales),
        best_employee["Name"],
        best_product["Product"],
        best_department["Department"]
    ]
})

In [47]:
summary

            Metric   Value
0    Total Revenue  338500
1     Total Orders      10
2    Best Employee   Frank
3     Best Product  Laptop
4  Best Department      HR

In [48]:
city_report = (
    sales_details
    .groupby("City")
    .agg(
        Orders=("OrderID", "count"),
        TotalQuantity=("Quantity", "sum"),
        TotalRevenue=("Revenue", "sum")
    )
    .reset_index()
)

In [49]:
city_report = city_report.sort_values(
    "TotalRevenue",
    ascending=False
)

In [50]:
category_report = (
    sales_details
    .groupby("Category")
    .agg(
        Orders=("OrderID", "count"),
        TotalQuantity=("Quantity", "sum"),
        TotalRevenue=("Revenue", "sum")
    )
    .reset_index()
)

In [51]:
category_report = category_report.sort_values(
    "TotalRevenue",
    ascending=False
)

In [52]:
with pd.ExcelWriter(
    "output/company_analysis_report.xlsx"
) as writer:

    summary.to_excel(
        writer,
        sheet_name="Executive Summary",
        index=False
    )

    department_report.to_excel(
        writer,
        sheet_name="Department Report",
        index=False
    )

    employee_report.to_excel(
        writer,
        sheet_name="Employee Report",
        index=False
    )

    product_report.to_excel(
        writer,
        sheet_name="Product Report",
        index=False
    )

    city_report.to_excel(
        writer,
        sheet_name="City Report",
        index=False
    )

    category_report.to_excel(
        writer,
        sheet_name="Category Report",
        index=False
    )

    sales_details.to_excel(
        writer,
        sheet_name="Sales Details",
        index=False
    )

In [53]:
report = pd.ExcelFile(
    "output/company_analysis_report.xlsx"
)

In [55]:
report.sheet_names

['Executive Summary',
 'Department Report',
 'Employee Report',
 'Product Report',
 'City Report',
 'Category Report',
 'Sales Details']

In [56]:
executive_summary = pd.read_excel(
    report,
    sheet_name="Executive Summary"
)